insert into USUARIO (nome_completo, cpf, nome_social, data_nascimento, genero, email, senha)
values
('Gustavo Machado Raimundo', '48589520889', 'Xoba', '2001-08-10', 'M', 'gustavo@email.com','1234'),
('Emanuelle de Araújo Alves', '43713814805','Manu','2001-04-02', 'F', 'Emanuelle.araujoa7@gmail.com', '123'),
('Fernando Maia Noronha','32466132818','Maia', '2000-11-28', 'M', 'fernandom281100@gmail.com', '23456'),
('João Alfredo','23908736791', 'João', '1990-02-12', 'M', 'joaoalfredo@gmail.com', '34567'),
('Guilherme Mingardi','56843218987', 'Gui', '2001-03-04', 'M', 'guilhermemingardi@gmail.com', '56789'),
('Bianca Barranco','89456135498', 'Bi', '1991-05-23', 'F', 'biancabarranco@gmail.com', '124457'),
('Alex Parreira','563174894214', 'Parreira', '1980-04-27', 'M', 'alexparreira@gmail.com', '098765'),
('Rayann Silvestre Silva','12346546884', 'Rayann', '2001-09-21', 'M', 'rayannsilvestre@gmail.com', '19182'),
('Andre Gomes Cunha','87126354984', 'Deh', '1998-03-22', 'M', 'andregomes@gmail.com', '910291'),
('Carol Vieira','516846152638', 'Vieira', '2000-03-19', 'F', 'carolvieira@gmail.com', '2321323'),
('Ana Roberta','1265486915', 'Roberta', '2000-05-13', 'F', 'anaroberta@gmail.com', '2019201'),
('Daniel Maia Antonio','46846418353', 'Dani', '1982-03-22', 'M','danielmaia@gmail.com','0921081');

insert into INTERESSES (STATUS_DIA, ACOMPANHADO, FK_USUARIO)
values
('FELIZ', 'SOZINHO', 1),
('ENTEDIADO', 'SOZINHO', 2),
('FOGOSO','NAMORADE', 3),
('ANIMADO','NAMORADE', 4),
('COM_FOME','CASADE', 5),
('DESANIMADO','AMIGOS', 6),
('FOGOSO', 'CASADE', 7),
('FELIZ', 'PET', 8),
('COM_FOME', 'SOZINHO', 9),
('ANIMADO', 'PET', 10);

insert into TIPO_ESTABELECIMENTO_USUARIO (INTERESSES_ID, ESTILO_ROLE)
values
(1, 'RESTAURANTE'),
(1, 'BAR'),
(1, 'PUB'),
(2, 'RESTAURANTE'),
(2, 'BAR'),
(2, 'PUB'),
(3, 'BALADA'),
(3, 'BAR'),
(3, 'RESTAURANTE'),
(4, 'RESTAURANTE'),
(4, 'BAR'),
(4, 'PUB'),
(5, 'BAR'),
(5, 'PUB'),
(5, 'BALADA'),
(6, 'BAR'),
(6, 'RESTAURANTE'),
(6, 'PUB'),
(7, 'BAR'),
(7, 'PUB'),
(7, 'RESTAURANTE'),
(8, 'BAR'),
(8, 'PUB'),
(8, 'BALADA'),
(9, 'BAR'),
(9, 'RESTAURANTE'),
(9, 'PUB'),
(10, 'BAR'),
(10, 'PUB'),
(10, 'RESTAURANTE');

insert into TIPO_MUSICA_USUARIO (INTERESSES_ID, ESTILO_MUSICA)
values
(1, 'ROCK'),
(1, 'MPB'),
(1, 'JAZZ'),
(1, 'METAL'),
(1, 'ELETRONICA'),
(1, 'TRANCE'),
(2, 'ROCK'),
(2, 'FOLK'),
(2, 'POP'),
(2, 'MPB'),
(3, 'SERTANEJO'),
(3, 'PAGODE'),
(3, 'FUNK'),
(3, 'ELETRONICA'),
(4, 'MPB'),
(4, 'JAZZ'),
(4, 'METAL'),
(4, 'ELETRONICA'),
(5, 'METAL'),
(5, 'ELETRONICA'),
(5, 'TRANCE'),
(5, 'ROCK'),
(6, 'FOLK'),
(6, 'POP'),
(6, 'MPB'),
(6, 'ELETRONICA'),
(7, 'SERTANEJO'),
(7, 'PAGODE'),
(7, 'FUNK'),
(7, 'ELETRONICA'),
(8, 'RAP'),
(8, 'ELETRONICA'),
(8, 'ROCK'),
(8, 'MPB'),
(9, 'FOLK'),
(9, 'POP'),
(9, 'MPB'),
(9, 'ELETRONICA'),
(10, 'ELETRONICA'),
(10, 'SERTANEJO'),
(10, 'PAGODE'),
(10, 'FUNK');

insert into ESTABELECIMENTO (NOME_FANTASIA, RAZAO_SOCIAL, EMAIL_CONTATO, CNPJ, CEP, MEDIA_PRECO, HORARIO_ABRE, HORARIO_FECHA, ENDERECO, NUMERO_ENDERECO, COMPLEMENTO, NOTA, FOTO, DESCRICAO, PARA_MAIORES)
values
('Recanto','Recanto', '','89498498489', '01416-001', '$', 15.00, 23.00,  'R. da Consolação - Cerqueira César - São Paulo - SP', 1,'', 7.5, 'https://lh3.googleusercontent.com/p/AF1QipPfPwOsr4RQ8EtRZpApQGtvgwl9AsrMiO5YSRQR=s1600-w1920', 'Restobar rústico e aconchegante serve opções de petiscos mistos da casa com área externa e boemia familiar.', true),
('Selva Club', 'Selva Club','', '08004177000', '01304-001', '$', 15.00, 23.00,  'R. Augusta  - Consolação - São Paulo - SP', 232,'', 6.8,'https://i.ibb.co/mH2WfKF/selva.jpg', 'A balada tem um som eclético, recebe bandas e DJs para agitar a pista de dança que conta com mezanino e bar.', true),
('Blitz Haus', 'Blitz Haus', '', '17274858000', '01305-000', '$', 15.00, 23.00,  ' R. Augusta - Consolação - São Paulo - SP', 534,'',  3.7,'https://i.ibb.co/MBDjLd3/blitz-dreams.jpg', 'Dividida em três ambientes, a casa tem restaurante com petiscos e drinks, uma pista moderna e andar de games.', true),
('La Sabrosa','La Sabrosa', '', '19909380000', '01304-001', '$', 15.00, 23.00,   'R. Augusta - Consolação - São Paulo - SP', 5345,'', 7.4,'https://i.ibb.co/DftqcQN/lasabrosa.jpg', 'Lanchonete de especialidades mexicanas expressas turbinadas com ingredientes seletos, em espaço estilizado.', true),
('Bar Bela Santos', 'Bar Bela Santos', '', '00127328000', '01418-200',  '$', 15.00, 23.00,   'Alameda Santos - Jardim Paulista - São Paulo - SP', 6254,'', 9.4,'https://i.ibb.co/y0BpSzq/bela-santos.jpg', 'O boteco simples e aconchegante é famoso por seus petiscos diferenciados e pelo chope cremoso.', true),
('Patná Bar e Lanchonete', 'Patná Bar e Lanchonete', '', '43385251000', '01305-100', '$', 15.00, 23.00,  'R. Augusta - Cerqueira César - São Paulo - SP', 4234,'',5.9,'https://i.ibb.co/GCZrWxG/patna-bar.jpg','Bar muito aconchegante e na melhor região de São Paulo, ótimo ambiente, com boa música e clima descontráido', true),
('Savana Bar', 'Savana Bar', '', '06962000144', '01410-001', '$', 15.00, 23.00, 'Alameda Min. Rocha Azevedo - Jardim Paulista - São Paulo - SP', 5423,'',10.0,'https://i.ibb.co/8NhpWJq/savana.jpg','Ambiente lindo, com um ótimo espaço para curtir com os amigos e família, música ao vivo, ótima comida e uma  localização muito segura', true),
('Athenas Restaurante', 'Athenas Restaurante', '', '05116212000', '01305-100', '$', 15.00, 23.00,  'R. Augusta - Consolação - São Paulo - SP', 1223,'', 10.0,'https://i.ibb.co/Lxf8B2C/atenas.jpg', 'Culinária contemporânea com toque grego, em restaurante de decoração moderna e buffet de pratos variados.', true),
('Violeta Bar e Restaurante', 'Violeta Bar e Restaurante', '','60827615000', '01305-100', '$', 15.00, 23.00,  'R. Augusta - Consolação - São Paulo - SP', 23423,'', 7.7,'https://i.ibb.co/SXwkrsr/violeta.jpg', 'Tradicional bar com cervejas e pratos executivos, ponto de encontro de vários públicos em rua de clima boêmio.', true),
('Beer House', 'Beer House', '', '28705336000', '01304-001', '$', 15.00, 23.00,  ' R. Augusta - Consolação - São Paulo - SP', 12312,'', 8.6,'https://i.ibb.co/nbJxXqp/beer-house.jpg', 'O bom do fim de semana é a gente que faz. Seu novo point para aquele happy hour com os amigos tem local marcado.', true);

insert into TAGS_ESTABELECIMENTO (FK_ESTABELECIMENTO)
values
(1),
(2),
(3),
(4),
(5),
(6),
(7),
(8),
(9),
(10);


insert into CARACTERISTICA_ESTABELECIMENTO (TAGS_ESTABELECIMENTO_ID, CARACTERISTICAS)
values
(1, 'ANIMADO'),
(1, 'FOGOSO'),
(1, 'FELIZ'),
(1, 'COM_FOME'),
(2, 'FOGOSO'),
(2, 'ANIMADO'),
(2, 'FELIZ'),
(2, 'ENTEDIADO'),
(2, 'DESANIMADO'),
(3, 'ANIMADO'),
(3, 'FOGOSO'),
(3, 'FELIZ'),
(3, 'ENTEDIADO'),
(3, 'DESANIMADO'),
(3, 'COM_FOME'),
(4, 'COM_FOME'),
(4, 'DESANIMADO'),
(5, 'FELIZ'),
(5, 'FOGOSO'),
(5, 'ENTEDIADO'),
(5, 'DESANIMADO'),
(5, 'ANIMADO'),
(5, 'COM_FOME'),
(6, 'FOGOSO'),
(6, 'FELIZ'),
(6, 'ANIMADO'),
(6, 'COM_FOME'),
(7, 'ANIMADO'),
(7, 'FELIZ'),
(7, 'COM_FOME'),
(8, 'FELIZ'),
(8, 'ANIMADO'),
(8, 'COM_FOME'),
(9, 'FELIZ'),
(9, 'ANIMADO'),
(9, 'COM_FOME'),
(9, 'ENTEDIADO'),
(10, 'FOGOSO'),
(10, 'ANIMADO'),
(10, 'FELIZ'),
(10, 'ENTEDIADO'),
(10, 'DESANIMADO'),
(10, 'COM_FOME');

insert into TIPO_ESTABELECIMENTO (TAGS_ESTABELECIMENTO_ID, TIPO_ESTABELECIMENTO)
values
(1, 'BAR'),
(2, 'BALADA'),
(3, 'PUB'),
(4, 'RESTAURANTE'),
(5, 'BAR'),
(6, 'BAR'),
(7, 'BAR'),
(8, 'RESTAURANTE'),
(9, 'RESTAURANTE'),
(10, 'PUB');

insert into ACOMPANHAMENTO_ESTABELECIMENTO (TAGS_ESTABELECIMENTO_ID, TIPO_ACOMPANHAMENTO)
values
(1, 'SOZINHO'),
(1, 'AMIGOS'),
(1, 'NAMORADE'),
(2, 'AMIGOS'),
(2, 'NAMORADE'),
(2, 'SOZINHO'),
(3, 'AMIGOS'),
(3, 'NAMORADE'),
(4, 'CASADE'),
(4, 'NAMORADE'),
(4, 'AMIGOS'),
(5, 'AMIGOS'),
(5, 'NAMORADE'),
(5, 'CASADE'),
(5, 'SOZINHO'),
(5, 'PET'),
(6, 'AMIGOS'),
(7, 'AMIGOS'),
(7, 'NAMORADE'),
(7, 'CASADE'),
(8, 'SOZINHO'),
(8, 'CASADE'),
(8, 'NAMORADE'),
(8, 'AMIGOS'),
(9, 'AMIGOS'),
(9, 'SOZINHO'),
(10, 'AMIGOS'),
(10, 'CASADE'),
(10, 'NAMORADE');


insert into TIPO_MUSICA_ESTABELECIMENTO (TAGS_ESTABELECIMENTO_ID, ESTILO_MUSICA)
values
(1, 'FUNK'),
(1, 'SERTANEJO'),
(1, 'MPB'),
(1, 'PAGODE'),
(2, 'ROCK'),
(2, 'FOLK'),
(2, 'POP'),
(2, 'MPB'),
(3, 'SERTANEJO'),
(3, 'PAGODE'),
(3, 'FUNK'),
(3, 'ELETRONICA'),
(4, 'MPB'),
(4, 'JAZZ'),
(4, 'METAL'),
(4, 'ELETRONICA'),
(5, 'METAL'),
(5, 'ELETRONICA'),
(5, 'TRANCE'),
(5, 'ROCK'),
(6, 'FOLK'),
(6, 'POP'),
(6, 'MPB'),
(6, 'ELETRONICA'),
(7, 'SERTANEJO'),
(7, 'PAGODE'),
(7, 'FUNK'),
(7, 'ELETRONICA'),
(8, 'RAP'),
(8, 'ELETRONICA'),
(8, 'ROCK'),
(8, 'MPB'),
(9, 'FOLK'),
(9, 'POP'),
(9, 'MPB'),
(9, 'ELETRONICA'),
(10, 'ELETRONICA'),
(10, 'SERTANEJO'),
(10, 'PAGODE'),
(10, 'FUNK');

insert into EVENTO (NOME, HORARIO, DATA, TEMA, PRECO, ESTILO_MUSICA, FK_ESTABELECIMENTO)
values
('Reunião dos Bandtec', '22:00:00', '2020-04-20', 'Role', '10', 'Ópera', 1);

insert into USUARIO_ESTABELECIMENTO (FK_USUARIO, FK_ESTABELECIMENTO)
values
(3, 1);

insert into COMENTARIO (COMENTARIO, FK_ESTABELECIMENTO, FK_USUARIO) values
('Ambiente muito aconchegante, sempre que vou me sinto em casa! Músicas muito boas.', 10, 1 ),
('Ótimo lugar para se reunir com os amigos, sempre minha primeira opção de rolê. Nota 10.', 10, 2 ),
('Comidas e bebidas muito boas e no preço! Ambiente super massa com músicas de qualidade', 10, 3 ),
('Uma das melhores baladas que já fui, ambiente limpo e bastante organizado.', 2, 4 ),
('A segurança do local não deixou a desejar. Muito bom! .', 2, 5 ),
('Amei esse lugar, as bandas que frequentam lá são sempre de ótima qualidade e o preço está na média.', 2, 6 );
